### ISSUE TITLE
Setup Guide

### ISSUE THREAD

**Issue by alessiodam** [Drop-OSS/drop#1]
Hello, I've currently got the Drop server running using `yarn dev` but there are no guides on creating an account.  
Could you please extend the README.md to include all that info?

**Comment by DecDuck** [comment]
Just updated!

FYI, the register process will have to be overhauled with invitations, first time admin creation etc etc.

**Comment by alessiodam** [comment]
Thanks! I really can't wait to see where this insane project is going :P
