### ISSUE TITLE
Postgress FATAL error: role "root" does not exist  (Bug)

### ISSUE THREAD

**Issue by AdenMGB** [Drop-OSS/drop#11]
Hello, after creating the admin account via the **DropOSS WebUI** I can _sign into_ the account but the admin dashboard does **not** work, and every time that page is visited this error shows up in the logs:
`droposs-postgres-1  | 2024-12-25 23:26:18.529 UTC [73] FATAL:  role "root" does not exist`

### Secondly when visiting the features page this error appears

![image_2024_12_25T23_28_24_713Z](https://github.com/user-attachments/assets/17ca1acd-ed71-4eca-9d95-834a8f3865da)

### I have tried running the containers as root to no avail, and when trying to connect a client to the instance this error appears:

![image](https://github.com/user-attachments/assets/175346f1-6913-4a60-8889-4e978141cb49)

I am running the database and DropOSS in the same container and running through Dockge on **TrueNAS Scale.**

Hope we can find a solution!

Sincerely, Aden

**Comment by DecDuck** [comment]
Hey!

You can safely ignore the error in the PostgreSQL container, it's using the `drop` user instead. We'll update the `compose.yaml` with some flags that'll hide this messages to avoid confusion.

About the admin page, only a few pages are implemented at the moment, so that's expected. You should be able to visit the Home, Library and Auth pages without a 404 error.

For the client error, could you please upload the logs so I can take a look at them? They should be:
- On Windows, in `%appdata%/drop`
- On Linux, in `~/.local/share/drop/`

Looking for `drop.log`

Thanks :)

**Comment by AdenMGB** [comment]
Sorry for the such late response!

So here is the lowdown, I use _CloudFlare_ for my domain name and **Nginx Proxy Manager** for the reverse proxies. The DNS type is set to DNS only, and I've tried exposing the service port then using duckdns for a more direct connection if that makes any difference.

### Drop app client logs here (Windows)

**_[drop.log](https://github.com/user-attachments/files/18251838/drop.log)_**



**_Sincerely, Aden_**

**Comment by DecDuck** [comment]
That's all good.

Can you check the time on your server and client? Drop clients use cryptographically signed 'nonce's that expire within +-30 seconds of being generated. If your server and client are more than 30 seconds out of sync, every request the the client makes will be treated as invalid (hence the failure).

By the way, the logs expose the domain name you're hosting your Drop server on, so maybe delete it if you want to keep that top secret lmao - sorry for not mentioning it earlier.

**Comment by AdenMGB** [comment]
Thanks @DecDuck, that was the issue, you might want to have a little footnote in the documentation about that lol, or maybe like in the app say that the times are out of sync maybe. Basically I just set the primary ntp server to time.windows.com on the server side. Thanks so much for the help and I hope I can help you guys iron out some more little nuances for release!

Sincerely, Aden

**Comment by DecDuck** [comment]
Yep! Definitely going on the documentation, just wanted to confirm that was the issue.

Glad I could help you, you've definitely helped me.
