### ISSUE TITLE
feat: implement proper registration process

### ISSUE THREAD

**Issue by DecDuck** [Drop-OSS/drop#2]
Requirements:
 1. First time admin creation (detect with no users in database)
 2. Invitation-based account creation, with support for pre-filling userdata. Will eventually need to integrate with admin UI

**Comment by alessiodam** [comment]
Yes, I was thinking about making it invite only on self hosted servers.

**Comment by DecDuck** [comment]
Automatic provision by SSO is also a good feature to add

**Comment by alessiodam** [comment]
Yeah but why not first get the basic stuff working :P

**Comment by DecDuck** [comment]
Yeah of course, priorities are important. I was just mentioning it for later down the line.
